### ISSUE TITLE
invalid literal for int() with base 10: 'PT5S'

### ISSUE THREAD

**Issue by igarny** [perfsonar/mesh-config#35] opened 2016-10-26 09:21 UTC
Hi Andy,

The excerpt is from the meshconfig-agent.log: 

2016/10/26 08:52:53 (9416) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 500 INTERNAL SERVER ERROR: Unable to determine duration of test: Traceback (most recent call last):
  File "/usr/libexec/pscheduler/commands/../classes/tool/bwctliperf3/duration", line 26, in <module>
    duration += int(json['omit'])
ValueError: invalid literal for int() with base 10: 'PT5S'

On the link (http://pertcs01.switch.ch/report-mesh-err.tar.gz) you will find:
- meshconfig json
- mesh agent log
- mesh agent tasks

**Comment by daldoyle** [comment] 2016-10-26 13:11
This is a known issue with bwctliperf3 things, dupe of https://github.com/perfsonar/pscheduler/issues/192 and will be fixed there this week I believe.

**Closed as completed by daldoyle** 2016-10-26 13:12 UTC
