### ISSUE TITLE
meschconfig does not instantiate rtt tests from remote to local

### ISSUE THREAD

**Issue by igarny** [perfsonar/mesh-config#97] opened 2017-07-12 15:57 UTC
Hi Andy,

wrt the ping misses on the pSDev testbed and as reported in #96 

I have found these events in my logs (excerpt):

```
2017/07/12 16:10:37 (23657) WARN> perfsonar_meshconfig_agent:440 main:: - Problem determining which pscheduler to submit test to for creation, skipping test rtt(ps-4-0.qalab.geant.net->t2-psdev.rrze.uni-erlangen.de): 500 timeout
: 500 timeout

2017/07/12 16:10:37 (23657) WARN> perfsonar_meshconfig_agent:440 main:: - Problem determining which pscheduler to submit test to for creation, skipping test rtt(ps-4-0-xenial.qalab.geant.net->t2-psdev.rrze.uni-erlangen.de): 500 timeout
: 500 timeout

2017/07/12 16:10:37 (23657) WARN> perfsonar_meshconfig_agent:440 main:: - Problem determining which pscheduler to submit test to for creation, skipping test rtt(pstest.geant.carnet.hr->t2-psdev.rrze.uni-erlangen.de): 500 timeout
: 500 timeout

2017/07/12 16:10:37 (23657) WARN> perfsonar_meshconfig_agent:440 main:: - Problem determining which pscheduler to submit test to for creation, skipping test rtt(pstest2.geant.carnet.hr->t2-psdev.rrze.uni-erlangen.de): 500 timeout
: 500 timeout
```

I have produced this successful CLI test. Please note the test negotiation did not need any binding options to operate. Nevertheless because of my other mesh there are some binding options specified #96 , which obviously did not have an interference with the other tests (traceroute, throughput, latency)

```
t2-psdev:~>pscheduler task --debug rtt --count 10 --source antg-staging.es.net --interval PT1S --ip-version 4 --dest t2-psdev.rrze.uni-erlangen.de --length 1000
2017-07-12T16:52:14 Debug signal ignored; already not debugging
2017-07-12T16:52:14 Debug discontinued
2017-07-12T16:52:14 Assistance is from localhost
2017-07-12T16:52:14 Forcing default slip of PT5M
2017-07-12T16:52:14 Converting to spec via https://localhost/pscheduler/tests/rtt/spec
Submitting task...
2017-07-12T16:52:14 Fetching participant list
2017-07-12T16:52:14 Spec is: {"count": 10, "source": "antg-staging.es.net", "length": 1000, "dest": "t2-psdev.rrze.uni-erlangen.de", "interval": "PT1S", "ip-version": 4, "schema": 1}
2017-07-12T16:52:15 Got participants: {u'participants': [u'antg-staging.es.net']}
2017-07-12T16:52:15 Lead is antg-staging.es.net
2017-07-12T16:52:15 Pinging https://antg-staging.es.net/pscheduler/
2017-07-12T16:52:16 antg-staging.es.net is up
2017-07-12T16:52:16 Posting task to https://antg-staging.es.net/pscheduler/tasks
2017-07-12T16:52:16 Data is {"test": {"type": "rtt", "spec": {"count": 10, "source": "antg-staging.es.net", "length": 1000, "dest": "t2-psdev.rrze.uni-erlangen.de", "interval": "PT1S", "ip-version": 4, "schema": 1}}, "schedule": {"slip": "PT5M"}, "schema": 1}
Task URL:
https://antg-staging.es.net/pscheduler/tasks/f8d0063d-99d5-4e52-be68-944021eb5b69
2017-07-12T16:52:23 Posted https://antg-staging.es.net/pscheduler/tasks/f8d0063d-99d5-4e52-be68-944021eb5b69
Running with tool 'ping'
Fetching first run...
2017-07-12T16:52:24 Fetching https://antg-staging.es.net/pscheduler/tasks/f8d0063d-99d5-4e52-be68-944021eb5b69/runs/first
2017-07-12T16:52:29 Handing off: pscheduler watch --format text/plain --debug https://antg-staging.es.net/pscheduler/tasks/f8d0063d-99d5-4e52-be68-944021eb5b69
2017-07-12T16:52:29 Debug signal ignored; already not debugging
2017-07-12T16:52:29 Debug discontinued
2017-07-12T16:52:29 Fetching https://antg-staging.es.net/pscheduler/tasks/f8d0063d-99d5-4e52-be68-944021eb5b69

Next scheduled run:
https://antg-staging.es.net/pscheduler/tasks/f8d0063d-99d5-4e52-be68-944021eb5b69/runs/76254826-bf88-4ab8-9582-ba0bf196d7b0
Starts 2017-07-12T07:52:36-07:00 (~3 seconds)
Ends   2017-07-12T07:52:52-07:00 (~15 seconds)
Waiting for result...

1       t2-psdev.rrze.uni-erlangen.de (131.188.81.82)  1008 Bytes  TTL 48  RTT 170.0000 ms
2       t2-psdev.rrze.uni-erlangen.de (131.188.81.82)  1008 Bytes  TTL 48  RTT 177.0000 ms
3       t2-psdev.rrze.uni-erlangen.de (131.188.81.82)  1008 Bytes  TTL 48  RTT 170.0000 ms
4       t2-psdev.rrze.uni-erlangen.de (131.188.81.82)  1008 Bytes  TTL 48  RTT 170.0000 ms
5       t2-psdev.rrze.uni-erlangen.de (131.188.81.82)  1008 Bytes  TTL 48  RTT 171.0000 ms
6       t2-psdev.rrze.uni-erlangen.de (131.188.81.82)  1008 Bytes  TTL 48  RTT 170.0000 ms
7       t2-psdev.rrze.uni-erlangen.de (131.188.81.82)  1008 Bytes  TTL 48  RTT 170.0000 ms
8       t2-psdev.rrze.uni-erlangen.de (131.188.81.82)  1008 Bytes  TTL 48  RTT 170.0000 ms
9       t2-psdev.rrze.uni-erlangen.de (131.188.81.82)  1008 Bytes  TTL 48  RTT 170.0000 ms
10      t2-psdev.rrze.uni-erlangen.de (131.188.81.82)  1008 Bytes  TTL 48  RTT 171.0000 ms

0% Packet Loss  RTT Min/Mean/Max/StdDev = 170.649000/171.504000/177.486000/2.079000 ms

No further runs scheduled.
```

**Comment by igarny** [comment] 2017-07-12 16:10
![psdev testbed ping martix](https://user-images.githubusercontent.com/11942774/28127589-6412c758-672d-11e7-920d-e9d7bedddbb2.jpg)

**Comment by igarny** [comment] 2017-07-14 11:33
Yesterday I have removed the second mesh configuration and have kept only the pSDev Testbed mesh. The results is - the measurements have been recovered.
![psdev testbed ping martix2](https://user-images.githubusercontent.com/11942774/28210711-000afca4-6899-11e7-95ac-20487516a04c.jpg)

**Comment by arlake228** [comment] 2017-08-31 12:30
Is this still an issue? Looks like it has gone away and don't know that I have enough info to recreate at this point.

**Comment by igarny** [comment] 2017-09-11 15:58
In fact this issue is the same or a subtopic of #98

**Comment by arlake228** [comment] 2017-09-25 13:35
Closing this because Ivan did a good job explaining to me that it actually caused by #98, basically when you have 2 meshes the global bind option that gets set can conflict with the bind options of the other mesh.

**Closed as completed by arlake228** 2017-09-25 13:35 UTC
Labels: bug
